## Test code for defining an indpendent simple fem simulation  

In [4]:
from dolfin import *
import numpy as np

class boundary(SubDomain):
    def inside(self, x, on_boundary):
        return x[0] < 0.4 and on_boundary

mesh = UnitCubeMesh(5,5,5)
V = FunctionSpace(mesh, "CG", 1)
v = project(Expression("x[0]*x[1]+x[2]", degree=2),V)
mf = MeshFunction("size_t", mesh, mesh.topology().dim()-1, 0)
boundary().mark(mf, 1)
v2d = vertex_to_dof_map(V)
dofs = []
for facet in facets(mesh):
    if mf[facet.index()] == 1:
        vertices = facet.entities(0)
        for vertex in vertices:
            dofs.append(v2d[vertex])

unique_dofs = np.array(list(set(dofs)), dtype=np.int32)
boundary_coords = V.tabulate_dof_coordinates()[unique_dofs]
for i, dof in enumerate(unique_dofs):
    print(boundary_coords[i], v.vector()[dof])


[0. 0. 1.] 0.9951197728380257
[0.  0.  0.8] 0.794865277732957
[0.2 0.2 1. ] 1.0368804569557282
[0.2 0.  1. ] 0.9980147196352503
[0.  0.2 1. ] 0.9980147196352502
[0.  0.  0.6] 0.5951651995296948
[0.2 0.4 0. ] 0.07672562571440637
[0.  0.4 0. ] -0.0037072775371934453
[0.2 0.  0.8] 0.7967364114245992
[0.  0.6 0.2] 0.19673283903097083
[0.  0.2 0.8] 0.7967364114245993
[0.  0.8 0.4] 0.3962528529285646
[0.2 1.  0.6] 0.7962528529285579
[0.  1.  0.6] 0.599732412804788
[0.  0.  0.4] 0.3951279981479135
[0.  0.4 1. ] 0.997374230653248
[0.2 0.  0.6] 0.5968751997046994
[0.2 0.4 1. ] 1.0764035394098912
[0.  0.2 0.6] 0.5968751997046986
[0.  0.4 0.8] 0.7965785824662885
[0.2 0.6 1. ] 1.1165850057800875
[0.  0.6 1. ] 0.9974022351008058
[0.  0.  0.2] 0.1950854681576532
[0.2 0.  0.4] 0.3968842638395435
[0.  0.2 0.4] 0.3968842638395435
[0.2 0.6 0. ] 0.11667730860103398
[0.  0.6 0. ] -0.0036375132649267006
[0.  0.4 0.6] 0.5966680745786419
[0.  0.8 0.2] 0.1963212280161968
[0.2 1.  0.4] 0.5961947937348213
[0.  

In [7]:
boundary_coords.shape
coor=V.tabulate_dof_coordinates()
# v.vector()[dof]
coor.shape

(216, 3)